# Generated by Django 4.2.26 on 2025-11-18 11:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import showcase.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_file', models.FileField(blank=True, help_text='Formats acceptés: .ico, .png, .jpg, .svg (max 5MB)', null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='showcase.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom campagne')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Planifiée pour')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sending', 'Envoi'), ('sent', 'Envoyée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne newsletter',
                'verbose_name_plural': 'Campagnes newsletter',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom template')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('plain_content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('html_content', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('is_active', models.BooleanField(default=True)),
                ('default_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template newsletter',
                'verbose_name_plural': 'Templates newsletter',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Description courte')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix (FCFA)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix barré')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de revient')),
                ('brand', models.CharField(db_index=True, max_length=100, verbose_name='Marque')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='SKU/Référence')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Code-barres')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='En stock')),
                ('stock_quantity', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Quantité en stock')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='showcase.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom promotion')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code (optionnel)')),
                ('promotion_type', models.CharField(choices=[('percent', 'Pourcentage'), ('amount', 'Montant fixe'), ('set_price', 'Prix fixé'), ('bogo', 'Buy X Get Y')], default='percent', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur')),
                ('buy_x', models.PositiveIntegerField(default=0, verbose_name='Buy X (pour BOGO)')),
                ('get_y', models.PositiveIntegerField(default=0, verbose_name='Get Y (pour BOGO)')),
                ('applies_to_all', models.BooleanField(default=False, verbose_name="S'applique à tous les produits")),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name="Limite d'utilisation globale")),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite par utilisateur')),
                ('is_stackable', models.BooleanField(default=False, verbose_name="Empilable avec d'autres promotions")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='showcase.category', verbose_name='Catégories ciblées')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='showcase.product', verbose_name='Produits ciblés')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-start_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Youtube', 'Youtube')], max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='229XXXXXXXXX', help_text='Format: 229XXXXXXXXX (sans le +)', max_length=20, verbose_name='Numéro WhatsApp')),
                ('contact_email', models.EmailField(default='contact@niasotac.com', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+229 00 00 00 00', max_length=20, verbose_name='Téléphone de contact')),
                ('contact_address', models.CharField(default='Cotonou, Bénin', max_length=200, verbose_name='Adresse')),
                ('company_name', models.CharField(default='NIASOTAC TECHNOLOGIE', max_length=100, verbose_name="Nom de l'entreprise")),
                ('company_description', models.TextField(default='Votre revendeur tech de confiance au Bénin. Produits de qualité à prix compétitifs.', verbose_name="Description de l'entreprise")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_links', models.ManyToManyField(blank=True, to='showcase.sociallink')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Vues')),
                ('whatsapp_click_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Clics WhatsApp')),
                ('last_viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Produit vedette')),
                ('is_recommended', models.BooleanField(db_index=True, default=False, verbose_name='Produit recommandé')),
                ('featured_score', models.FloatField(db_index=True, default=0.0, verbose_name='Score vedette')),
                ('recommendation_score', models.FloatField(db_index=True, default=0.0, verbose_name='Score recommandation')),
                ('force_featured', models.BooleanField(default=False, verbose_name='🔒 Forcer en vedette')),
                ('force_recommended', models.BooleanField(default=False, verbose_name='🔒 Forcer en recommandé')),
                ('exclude_from_featured', models.BooleanField(default=False, verbose_name='🚫 Exclure des vedettes')),
                ('exclude_from_recommended', models.BooleanField(default=False, verbose_name='🚫 Exclure des recommandations')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='showcase.product')),
            ],
            options={
                'verbose_name': 'Statut produit',
                'verbose_name_plural': 'Statuts produits',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), showcase.validators.validate_product_image_size], verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='showcase.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('subscribed', models.BooleanField(default=True, verbose_name='Abonné')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('confirmation_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('tags', models.CharField(blank=True, max_length=250, verbose_name='Tags (séparés par des virgules)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='showcase_ne_email_f97594_idx'), models.Index(fields=['confirmation_token'], name='showcase_ne_confirm_ab2c9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec')], default='sent', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='showcase.newslettercampaign')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.newslettersubscriber')),
            ],
            options={
                'verbose_name': 'Log newsletter',
                'verbose_name_plural': 'Logs newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='showcase.newslettersubscriber'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='showcase.newslettertemplate'),
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='showcase.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation promotion',
                'verbose_name_plural': 'Utilisations promotions',
                'indexes': [models.Index(fields=['promotion', 'user'], name='showcase_pr_promoti_a0e599_idx')],
                'unique_together': {('promotion', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='showcase_pr_code_0953c1_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['active', 'start_at', 'end_at'], name='showcase_pr_active_b26f93_idx'),
        ),
        migrations.AddIndex(
            model_name='productstatus',
            index=models.Index(fields=['is_featured', '-featured_score'], name='showcase_pr_is_feat_2ca63f_idx'),
        ),
        migrations.AddIndex(
            model_name='productstatus',
            index=models.Index(fields=['is_recommended', '-recommendation_score'], name='showcase_pr_is_reco_0965a5_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', '-is_primary', 'order'], name='showcase_pr_product_cdf326_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='showcase_pr_created_6ae8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='showcase_pr_categor_6438ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='showcase_pr_brand_fdf568_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='showcase_pr_price_6a8435_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterlog',
            index=models.Index(fields=['campaign', 'subscriber'], name='showcase_ne_campaig_bc3daa_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='showcase_ca_parent__c4a6df_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='showcase_category_tree_id_125d'),
        ),
    ]
